Feature/3 authorization
youngbogdanchik/dg-ip-react pull request #3
Opened 2023-03-01 20:28 UTC by youngbogdanchik

2023-03-01 22:20 UTC, vladdoletskiy requested changes

2023-03-01 22:20 UTC, vladdoletskiy commented on .env.example
> +#AUTH0
if it is real .env - remove .example

2023-03-01 22:20 UTC, vladdoletskiy commented on src/app/ui/app.tsx
> +  useEffect(() => {
no, we dont use Fx in ui

2023-03-01 22:20 UTC, vladdoletskiy commented on src/entities/session/model/store.ts
> +export const $auth = domain
domain.store

2023-03-01 22:20 UTC, vladdoletskiy commented on src/entities/session/model/store.ts
> +  .on(logoutFx.doneData, () => ({}))
if you dont use the data you returned - use logoutFx.done

2023-03-01 22:20 UTC, vladdoletskiy commented on src/entities/session/model/types.ts
> +export type User = {
why all optional?

2023-03-01 22:20 UTC, vladdoletskiy commented on src/features/session/login/login-button.tsx
> +  const loginHandler = async () => {
if you want run loginFx - you should use 1. event - loginRequested (forexample) - then in store use sample - clock: loginRequested , target: loginFx

2023-03-02 12:59 UTC, youngbogdanchik commented on src/features/session/login/login-button.tsx
> +  const loginHandler = async () => {
fixed

2023-03-02 12:59 UTC, youngbogdanchik commented on .env.example
> +#AUTH0
done

2023-03-02 12:59 UTC, youngbogdanchik commented on src/app/ui/app.tsx
> +  useEffect(() => {
fixed

2023-03-02 13:06 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +  .on(logoutFx.doneData, () => ({}))
done

2023-03-02 13:09 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +export const $auth = domain
done

2023-03-02 13:19 UTC, youngbogdanchik commented on src/entities/session/model/types.ts
> +export type User = {
because i reset {} when creating the store

2023-03-02 13:26 UTC, youngbogdanchik commented on src/entities/session/model/types.ts
> +export type User = {
please let me know if there is a better option

2023-03-02 15:12 UTC, youngbogdanchik commented on src/entities/session/model/types.ts
> +export type User = {
Fixed

2023-03-03 11:29 UTC, mmospanenko approved these changes
added comments, rework it firstly

2023-03-03 11:29 UTC, mmospanenko commented on src/app/ui/app.tsx
> +  useEffect(() => {
isAuthenticatedRequested
?

no, just inform the model about something happened. AppMounted, PageLoaded, etc.

and you can use Gate

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +const auth0 = await createAuth0Client(auth);
why to block app init, main thread?

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    console.error('Log in failed', err);
you should handle exceptions

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +      window.history.replaceState({}, '', '/home');
you can't know about app logic from here

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    console.error(e);
you have to throw an exception if user not authorized

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +export const isAuthenticatedRequested = createEvent();
use state instead, you shouldn't wait and request this all the time

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +export const loginRequested = createEvent();
with domain, you can use domain.event() instead of createEvent

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +export const $user = domain.store<Partial<User>>({});
Partial?

2023-03-03 11:29 UTC, mmospanenko commented on src/entities/session/model/types.ts
> +  email_verified: boolean;
email_verified is not part of user

2023-03-03 11:29 UTC, mmospanenko commented on src/features/session/login/login-button.tsx
> +  const loginHandler = () => {
avoid redundant code

2023-03-04 12:48 UTC, youngbogdanchik commented on src/features/session/login/login-button.tsx
> +  const loginHandler = () => {
done

2023-03-04 12:48 UTC, youngbogdanchik commented on src/entities/session/model/types.ts
> +  email_verified: boolean;
deleted

2023-03-04 12:48 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +export const $user = domain.store<Partial<User>>({});
fixed

2023-03-04 12:48 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +export const loginRequested = createEvent();
okay, updated

2023-03-04 12:49 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +    console.error(e);
done

2023-03-04 12:49 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +      window.history.replaceState({}, '', '/home');
deleted

2023-03-04 12:49 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +    console.error('Log in failed', err);
done

2023-03-04 12:49 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +const auth0 = await createAuth0Client(auth);
fixed

2023-03-05 20:20 UTC, youngbogdanchik commented on src/app/ui/app.tsx
> +  useEffect(() => {
Fixed

2023-03-05 20:24 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +export const isAuthenticatedRequested = createEvent();
Fixed

2023-03-06 09:40 UTC, vladdoletskiy approved these changes

2023-03-06 15:50 UTC, mmospanenko requested changes
1. wrong composition (features)
2. wrong types (user)
3. some style issues

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    return Promise.reject(new Error('Login failed'));
losing message context. use 
```ts
new Error(`Login failed: ${ originalMessage }`)
```

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    return Promise.reject(new Error('Logout failed'));
+

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +  try {
in try should be only one action

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    return false;
wrong try/catch logic

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +export const $auth = domain.store<boolean>(false);
use following ordering
1. events
2. effects
3. stores
4. logic

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +const getAuthStatusFx = domain.effect(getAuthStatus);
not sure that you need this on the app level

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/types.ts
> +export type TUser = {
wrong naming, maybe CurrentUser or Viewer?

2023-03-06 15:50 UTC, mmospanenko commented on src/entities/session/model/types.ts
> +  updated_at: string;
wrong style. And do you need this?

2023-03-06 15:50 UTC, mmospanenko commented on vite.config.ts
> +      '/': path.resolve(__dirname),
I don't know but it works without these aliases in our project

2023-03-07 14:56 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +    return Promise.reject(new Error('Login failed'));
Updated

2023-03-07 15:15 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +  try {
Fixed

2023-03-07 15:15 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +    return false;
Fixed

2023-03-07 15:15 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +export const $auth = domain.store<boolean>(false);
Updated

2023-03-07 15:15 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +const getAuthStatusFx = domain.effect(getAuthStatus);
Updated

2023-03-07 15:16 UTC, youngbogdanchik commented on src/entities/session/model/types.ts
> +export type TUser = {
Fixed

2023-03-07 15:16 UTC, youngbogdanchik commented on src/entities/session/model/types.ts
> +  updated_at: string;
Deleted

2023-03-07 15:18 UTC, youngbogdanchik commented on vite.config.ts
> +      '/': path.resolve(__dirname),
I don't know too. It doesn't work for me without those aliases

2023-03-07 15:25 UTC, vliashenko approved these changes

2023-03-07 15:34 UTC, mmospanenko requested changes
fix model exports and imports, use namespaces

2023-03-07 15:34 UTC, mmospanenko commented on src/app/ui/app.tsx
> +import React, { useEffect } from 'react';
always use React. as namespace

2023-03-07 15:34 UTC, mmospanenko commented on src/app/ui/app.tsx
> +import { appMounted } from 'entities/session';
import sessionModel

2023-03-07 15:34 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +import { auth } from 'shared/config';
auth ... config?

2023-03-07 15:34 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    return Promise.reject(new Error(`Not authenticated: ${err}`));
do you need this?

2023-03-07 15:34 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +import { CurrentUser } from 'entities/session/model/types';
export from entities/session

2023-03-07 15:34 UTC, mmospanenko commented on src/features/session/logout/logout-button.tsx
> +import { logoutRequested } from './model';
import * as model from './model' - we should know about model

2023-03-07 15:34 UTC, mmospanenko commented on src/features/session/logout/logout-button.tsx
> +  const logoutHandler = () => {
not necessary - write it inline

2023-03-07 15:34 UTC, mmospanenko commented on src/features/session/logout/model/model.ts
> +import { logoutFx } from 'entities/session/model';
import whole model

2023-03-07 15:34 UTC, mmospanenko commented on src/features/session/logout/model/model.ts
> +sample({ clock: logoutRequested, target: logoutFx });
avoid using external Fxs, use attach({effect: ...}) to copy it

2023-03-07 15:34 UTC, mmospanenko commented on src/shared/config/index.ts
> +export * from './auth';
auth?

2023-03-07 15:51 UTC, youngbogdanchik commented on src/app/ui/app.tsx
> +import React, { useEffect } from 'react';
Fixed

2023-03-07 15:55 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +import { CurrentUser } from 'entities/session/model/types';
fixed

2023-03-07 15:55 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +    return Promise.reject(new Error(`Not authenticated: ${err}`));
deleted

2023-03-07 15:55 UTC, youngbogdanchik commented on src/features/session/logout/logout-button.tsx
> +import { logoutRequested } from './model';
updated

2023-03-07 16:03 UTC, youngbogdanchik commented on src/features/session/logout/logout-button.tsx
> +  const logoutHandler = () => {
fixed

2023-03-07 16:03 UTC, youngbogdanchik commented on src/features/session/logout/model/model.ts
> +import { logoutFx } from 'entities/session/model';
updated

2023-03-07 17:59 UTC, youngbogdanchik commented on src/pages/home/ui/home-page.tsx
> +import { $user } from 'entities/session';
fixed

2023-03-07 18:11 UTC, youngbogdanchik commented on src/features/session/logout/model/model.ts
> +sample({ clock: logoutRequested, target: logoutFx });
done

2023-03-07 18:14 UTC, youngbogdanchik commented on src/app/ui/app.tsx
> +import { appMounted } from 'entities/session';
done

2023-03-07 18:15 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +import { auth } from 'shared/config';
renamed

2023-03-07 18:22 UTC, youngbogdanchik commented on vite.config.ts
> +      '/': path.resolve(__dirname),
Okay, now it works

2023-03-07 18:46 UTC, iNikolas commented on src/app/ui/app.tsx
> +  React.useEffect(() => {
Better to use hook `useGate` from effector-react for such needs

2023-03-07 18:46 UTC, iNikolas commented on src/entities/session/model/api.ts
> +import { CurrentUser } from 'entities/session/model/types';
For imports within the same module it's better to use relative imports

2023-03-07 18:46 UTC, iNikolas commented on src/entities/session/model/api.ts
> +    nickname: user?.nickname || '',
Only nickname. Why we are going without id?

2023-03-07 18:46 UTC, iNikolas commented on src/pages/home/ui/home-page.tsx
> +      style={{ minHeight: '100vh' }}
style for mui components? Mui is styled with `sx`

2023-03-07 18:46 UTC, iNikolas commented on src/pages/home/ui/home-page.tsx
> +              gap: '10px',
px prefix is unnecessary, just number

2023-03-07 18:54 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +    nickname: user?.nickname || '',
because auth0 does not provide an id

2023-03-07 18:55 UTC, youngbogdanchik commented on src/pages/home/ui/home-page.tsx
> +      style={{ minHeight: '100vh' }}
accidentally, fixed

2023-03-07 18:55 UTC, youngbogdanchik commented on src/pages/home/ui/home-page.tsx
> +              gap: '10px',
fixed

2023-03-07 19:03 UTC, youngbogdanchik commented on src/entities/session/model/api.ts
> +import { CurrentUser } from 'entities/session/model/types';
ide accidentally did this, fixed

2023-03-07 19:30 UTC, youngbogdanchik commented on src/app/ui/app.tsx
> +  React.useEffect(() => {
Updated

2023-03-07 20:14 UTC, mmospanenko approved these changes

2023-03-07 20:14 UTC, mmospanenko commented on package.json
> +    "effector-logger": "^0.13.7",
this is dev dependency

2023-03-07 20:14 UTC, mmospanenko commented on package.json
> +    "gh-pages": "^5.0.0",
not sure that we should use node for this)

2023-03-07 20:14 UTC, mmospanenko commented on src/entities/session/model/api.ts
> +    nickname: user?.nickname || '',
sub is id as I remember

2023-03-07 20:14 UTC, mmospanenko commented on src/entities/session/model/index.ts
>  export * from './api';
don't expose api from model

2023-03-07 20:14 UTC, mmospanenko commented on src/entities/session/model/store.ts
> +Gate.open(getCurrentUserFx());
hm... no, this is wrong

2023-03-07 20:14 UTC, mmospanenko commented on src/features/session/index.ts
> +export * from './logout';
no, you should describe export here

2023-03-07 20:14 UTC, mmospanenko commented on src/features/session/logout/logout-button.tsx
> +import React from 'react';
move this to /ui

2023-03-07 20:14 UTC, mmospanenko commented on src/features/session/logout/model.ts
> +sample({ clock: logoutRequested, target: logoutFx });
and what then? you forgot to close session on the Entity level

2023-03-07 20:28 UTC, youngbogdanchik commented on package.json
> +    "gh-pages": "^5.0.0",
just tried to deploy on the github page. deleted

2023-03-07 20:28 UTC, youngbogdanchik commented on package.json
> +    "effector-logger": "^0.13.7",
it is in dev dependency

2023-03-07 20:28 UTC, youngbogdanchik commented on src/features/session/logout/logout-button.tsx
> +import React from 'react';
done

2023-03-07 20:29 UTC, youngbogdanchik commented on src/entities/session/model/index.ts
>  export * from './api';
okay, deleted

2023-03-07 20:37 UTC, youngbogdanchik commented on src/entities/session/model/store.ts
> +Gate.open(getCurrentUserFx());
fixed

2023-03-07 20:48 UTC, youngbogdanchik commented on src/features/session/index.ts
> +export * from './logout';
deleted

2023-03-23 18:29 UTC, merged